#!/bin/bash
# Materialise every generated file that contains a secret, from .env.bash.
#
#   generated_config/dovecot/users     Dovecot passwd-file (ARGON2ID hash)
#   generated_config/mbsync/mbsyncrc   mbsync config (Gmail app password)
#
# Neither is committed. Re-run this after changing any credential in
# .env.bash, then restart the affected service (see docs/maintenance.md).
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env.bash"
[[ -f "$ENV_FILE" ]] || { echo "Error: $ENV_FILE not found. Copy .env.bash.template." >&2; exit 1; }
set -a; source "$ENV_FILE"; set +a

: "${ARCHIVE_USER:?not set in .env.bash}"
: "${ARCHIVE_PASSWORD:?not set in .env.bash}"
: "${DOVECOT_VERSION:?not set in .env.bash}"

if [[ "$ARCHIVE_PASSWORD" == "CHANGEME" ]]; then
  echo "Error: ARCHIVE_PASSWORD is still CHANGEME. Set a real one." >&2
  exit 1
fi

OUT_DIR="$(pwd)/generated_config/dovecot"
mkdir -p "$OUT_DIR"

# Hash using the same Dovecot version that will verify it.
echo "Hashing password with ARGON2ID..."
HASH="$(docker run --rm -i "dovecot/dovecot:${DOVECOT_VERSION}" \
          doveadm pw -s ARGON2ID -p "$ARCHIVE_PASSWORD")"

# passwd-file format: user:password:uid:gid:gecos:home:shell:extra
# The empty fields fall back to mail_uid / mail_gid / mail_home from
# config/dovecot/conf.d/10-archive.conf.
umask 077
printf '%s:%s::::::\n' "$ARCHIVE_USER" "$HASH" > "$OUT_DIR/users"
chmod 640 "$OUT_DIR/users"

echo "Wrote $OUT_DIR/users for user '${ARCHIVE_USER}'."

########################################
# mbsync configuration
########################################
: "${GMAIL_ADDRESS:?not set in .env.bash}"
: "${GMAIL_SOURCE_FOLDER:?not set in .env.bash}"
: "${ARCHIVE_FOLDER:?not set in .env.bash}"

MB_DIR="$(pwd)/generated_config/mbsync"
mkdir -p "$MB_DIR"

if [[ -z "${GMAIL_APP_PASSWORD:-}" ]]; then
  echo "Warning: GMAIL_APP_PASSWORD is empty - writing mbsyncrc anyway, but" >&2
  echo "         the sync will fail until it is set. See docs/initial-setup.md." >&2
fi

# The Maildir path Dovecot serves this user from, matching mail_home/mail_path
# in config/dovecot/conf.d/10-archive.conf. Inside the mbsync container the
# share is mounted at /srv/vmail, the same place Dovecot sees it.
MAIL_ROOT="/srv/vmail/$(echo "$ARCHIVE_USER" | tr '[:upper:]' '[:lower:]')/mail"

cat > "$MB_DIR/mbsyncrc" <<MBEOF
# Generated by scripts/gen-secrets.sh - DO NOT EDIT, changes are overwritten.
# Contains the Gmail app password.

########################################
# Far side: Gmail
########################################
IMAPAccount gmail
Host imap.gmail.com
Port 993
User ${GMAIL_ADDRESS}
Pass "${GMAIL_APP_PASSWORD:-}"
TLSType IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt
# Gmail throttles hard on a large initial pull and drops connections that ask
# for too much at once. Keep the pipeline shallow and the timeout generous.
PipelineDepth 10
Timeout 600

IMAPStore gmail-remote
Account gmail

########################################
# Near side: the archive Maildir
########################################
MaildirStore archive-local
Path ${MAIL_ROOT}/
Inbox ${MAIL_ROOT}/
# Dovecot uses mailbox_list_layout = fs, i.e. plain nested directories.
# Verbatim matches that. Maildir++ would write .dotted.names instead and
# Dovecot would not list the folder at all.
SubFolders Verbatim

########################################
# Channel
########################################
Channel gmail-archive
Far :gmail-remote:"${GMAIL_SOURCE_FOLDER}"
Near :archive-local:"${ARCHIVE_FOLDER}"
# NOTE: no blank lines anywhere inside this section. A blank line ENDS a
# section in mbsync config, and because Create/Remove/Expunge/Sync are also
# valid GLOBAL options they would be silently accepted as defaults instead of
# channel settings - no error, just not what was written. Only SyncState fails
# loudly ("global options may not follow sections"), which is how this was
# caught.
# Create the destination folder on the archive side if missing, never on Gmail.
Create Near
# Never propagate mailbox deletions.
Remove None
# Never expunge anything, anywhere. Belt and braces with Sync below.
Expunge None
# PullNew: copy new messages from Gmail to the archive and NOTHING else.
#
# This is the setting that makes deleting mail from Gmail safe. Plain "Pull"
# would also propagate deletions and flag changes, so emptying Gmail would
# empty the archive - the exact disaster this system exists to prevent.
# The cost is that read/unread state is not mirrored, which does not matter
# for an archive.
Sync PullNew
# Store the sync state as .mbsyncstate inside the destination folder.
# THIS LINE IS LOAD-BEARING. Without it mbsync 1.5 keeps no state at all and
# re-pulls the ENTIRE folder on every run, so each scheduled sync would add
# another complete copy of the archive. Verified: three consecutive runs
# without it produced 3 -> 6 -> 9 -> 12 messages; with it, 3 -> 3 -> 3.
# It is a Channel keyword: a MaildirStore block rejects it with
# "keyword 'SyncState' is not recognized".
# NOTE: no blank line above - in mbsync config a blank line ENDS the section,
# which would make this a global option and fail with
# "global options may not follow sections".
SyncState *
MBEOF

chmod 600 "$MB_DIR/mbsyncrc"

echo "Wrote $MB_DIR/mbsyncrc (${GMAIL_SOURCE_FOLDER} -> ${ARCHIVE_FOLDER})."
echo
echo "Restart Dovecot to pick up the password change:"
echo "  sudo systemctl restart imap-archive"
